[gen-ts-types]
description = "generates typescript types for the ts client"
path = "."
cmd = "node ./client/core/ts/generate_types.mjs"

[build-ts-client]
path = "client/core/ts"
cmd = "yarn build"

[start-frontend]
path = "frontend"
cmd = "yarn dev"

[build-frontend]
path = "frontend"
cmd = "yarn build"

[test-compose]
description = "deploys test.compose.yaml"
cmd = """
docker compose -f test.compose.yaml down && \
docker compose -f test.compose.yaml up --attach monitor-periphery"""

[test-core]
description = "runs core --release pointing to test.core.config.toml"
cmd = "MONITOR_CONFIG_PATH=test.core.config.toml cargo run -p monitor_core --release"

[update-periphery]
path = "."
cmd = """
cargo build -p monitor_periphery --release && \
systemctl stop periphery && \
cp ./target/release/periphery /usr/local/bin/periphery && \
chmod +x /usr/local/bin/periphery && \
systemctl start periphery"""

[docsite-start]
path = "docsite"
cmd = "yarn start"

[docsite-deploy]
path = "docsite"
cmd = "yarn deploy"

[rustdoc-server]
cmd = "cargo watch -s 'cargo doc --no-deps -p monitor_client' & http --quiet target/doc"