#################################
# 🦎 KOMODO PERIPHERY CONFIG 🦎 #
#################################
port = 8121
repo_dir = ".komodo/repos"
stack_dir = ".komodo/stacks"
stats_polling_rate = "1-sec"
legacy_compose_cli = false
include_disk_mounts = []

############
# Security #
############
ssl_enabled = true
ssl_key_file = ".komodo/ssl/key.pem"
ssl_cert_file = ".komodo/ssl/cert.pem"

###########
# LOGGING #
###########
logging.level = "info"
logging.stdio = "standard"
# logging.otlp_endpoint = "http://grafana.orb.local:4317"
logging.opentelemetry_service_name = "Periphery"