title = "Komodo Test"
host = "http://localhost:9121"
port = 9121
passkey = "a_random_passkey"
repo_directory = "/Users/max/komodo-repos"
disable_confirm_dialog = true
enable_new_users = true

# database.address = "localhost:27017"
# database.address = "ferretdb.komodo.orb.local"
database.address = "test-ferretdb.orb.local"
# database.username = "admin"
# database.password = "admin"
# database.uri = "mongodb://admin:admin@localhost:27017/komodo" # For ferretdb-postgres

local_auth = true
jwt_secret = "your_random_secret"
jwt_ttl = "2-wk"

webhook_secret = "a_random_webhook_secret"

stack_poll_interval = "1-min"
sync_poll_interval = "1-min"
build_poll_interval = "1-min"
repo_poll_interval = "1-min"
monitoring_interval = "5-sec"
