################################
# 🦎 KOMODO PERIPHERY CONFIG 🦎 #
################################
port = 8121
repo_dir = ".repos"
stack_dir = ".stacks"
stats_polling_rate = "1-sec"
legacy_compose_cli = false
include_disk_mounts = []

############
# Security #
############
ssl_enabled = false
ssl_key_file = ".ssl/key.pem"
ssl_cert_file = ".ssl/cert.pem"