title = "Komodo Test"
host = "http://localhost:9120"
passkey = "a_random_passkey"
ensure_server = "http://localhost:8120"
repo_directory = "/Users/max/komodo-repos"

mongo.address = "localhost:27017"
# mongo.username = "admin"
# mongo.password = "admin"
# mongo.uri = "mongodb://admin:admin@localhost:27017/komodo" # For ferretdb-postgres

local_auth = true
jwt_secret = "your_random_secret"
jwt_ttl = "2-wk"

webhook_secret = "a_random_webhook_secret"

stack_poll_interval = "1-min"
sync_poll_interval = "1-min"
build_poll_interval = "1-min"
repo_poll_interval = "1-min"
monitoring_interval = "5-sec"
