##########################
# KOMODO COMPOSE - MONGO #
##########################

## This compose file will bring up MongoDB, Komodo Core, and Komodo Periphery in containers.
## Mongo is the recommended database for Komodo.
## A "default" server pointing to the local Periphery will be waiting in the UI on first startup.

services:
  mongo:
    image: mongo
    command: --quiet # suppress mongo logs a bit
    restart: unless-stopped
    logging:
      driver: local # enable log rotation by default. see `https://docs.docker.com/config/containers/logging/local/`
    networks:
      - default
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  
  core:
    image: ghcr.io/mbecker20/komodo:latest
    # image: ghcr.io/mbecker20/komodo:latest-aarch64 ## Use for arm support
    restart: unless-stopped
    depends_on:
      - mongo
    logging:
      driver: local
    networks:
      - default
    ports:
      - 9120:9120
    # extra_hosts: # allows for systemd Periphery connection at "http://host.docker.internal:8120"
    #   - host.docker.internal:host-gateway
    environment: # https://github.com/mbecker20/komodo/blob/main/config_example/core.config.example.toml
      KOMODO_HOST: ${KOMODO_HOST} # CHANGEME
      KOMODO_TITLE: ${KOMODO_TITLE} # Change the app title, displayed in the browser tab.
      KOMODO_ENSURE_SERVER: http://periphery:8120 # Creates the "default" server.
      ## Mongo
      KOMODO_MONGO_ADDRESS: mongo:27017
      KOMODO_MONGO_USERNAME: ${DB_USERNAME}
      KOMODO_MONGO_PASSWORD: ${DB_PASSWORD}
      ## Secrets
      KOMODO_PASSKEY: ${KOMODO_PASSKEY} # used to auth against periphery
      KOMODO_WEBHOOK_SECRET: ${KOMODO_WEBHOOK_SECRET} # used to authenticate incoming webhooks
      KOMODO_JWT_SECRET: ${KOMODO_JWT_SECRET} # Optional. If empty, will have to log in again on restart.
      ## Auth
      KOMODO_LOCAL_AUTH: ${KOMODO_LOCAL_AUTH} # the default is false.
      ## Github Oauth
      # KOMODO_GITHUB_OAUTH_ENABLED: ${KOMODO_GITHUB_OAUTH_ENABLED}
      # KOMODO_GITHUB_OAUTH_ID: ${KOMODO_GITHUB_OAUTH_ID}
      # KOMODO_GITHUB_OAUTH_SECRET: ${KOMODO_GITHUB_OAUTH_SECRET}
      ## Google Oauth
      # KOMODO_GOOGLE_OAUTH_ENABLED: ${KOMODO_GOOGLE_OAUTH_ENABLED}
      # KOMODO_GOOGLE_OAUTH_ID: ${KOMODO_GOOGLE_OAUTH_ID}
      # KOMODO_GOOGLE_OAUTH_SECRET: ${KOMODO_GOOGLE_OAUTH_SECRET}
      ## Aws
      # KOMODO_AWS_ACCESS_KEY_ID: ${KOMODO_AWS_ACCESS_KEY_ID}
      # KOMODO_AWS_SECRET_ACCESS_KEY: ${KOMODO_AWS_SECRET_ACCESS_KEY}
      ## Hetzner
      # KOMODO_HETZNER_TOKEN: ${KOMODO_HETZNER_TOKEN}

  ## Deploy Periphery container using this block,
  ## or deploy the Periphery binary with systemd using https://github.com/mbecker20/komodo/tree/main/scripts
  periphery:
    image: ghcr.io/mbecker20/periphery:latest
    # image: ghcr.io/mbecker20/periphery:latest-aarch64 # Use for arm support
    logging:
      driver: local
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - repos:/etc/komodo/repos # manage repos in a docker volume, or change it to an accessible host directory.
      - stacks:/etc/komodo/stacks # manage stack files in a docker volume, or change it to an accessible host directory.
    environment:
      # If the disk size is overreporting, can use one of these to 
      # whitelist / blacklist the disks to filter them, whichever is easier.
      # Accepts comma separated list of paths.
      # Usually whitelisting just /etc/hostname gives correct size.
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      # PERIPHERY_EXCLUDE_DISK_MOUNTS: /snap,/etc/repos

volumes:
  mongo-data:
  mongo-config:
  repos:
  stacks:

networks:
  default: {}