services:
  komodo-core:
    image: ghcr.io/mbecker20/komodo:latest ## use ghcr.io/mbecker20/komodo:latest-aarch64 for arm support
    restart: unless-stopped
    depends_on:
      - komodo-mongo
    logging:
      driver: local # enable log rotation by default. see `https://docs.docker.com/config/containers/logging/local/`
    networks:
      - komodo-network
    ports:
      - 9120:9120
    extra_hosts: # allows for local periphery connection at "http://host.docker.internal:8120"
      - host.docker.internal:host-gateway
    environment: # https://github.com/mbecker20/komodo/blob/main/config_example/core.config.example.toml
      KOMODO_HOST: https://demo.komo.do
      KOMODO_TITLE: Komodo # Change the app title, displayed in the browser tab.
      ## MONGO
      KOMODO_MONGO_ADDRESS: komodo-mongo:27017
      KOMODO_MONGO_USERNAME: admin # match ones below
      KOMODO_MONGO_PASSWORD: admin
      ## KEYS
      KOMODO_PASSKEY: a_random_passkey # used to auth against periphery
      KOMODO_WEBHOOK_SECRET: a_random_secret # used to authenticate incoming webhooks
      KOMODO_JWT_SECRET: a_random_jwt_secret # Optional. If empty, will have to log in again on restart.
      ## AUTH
      KOMODO_LOCAL_AUTH: true # the default is false.
      # KOMODO_GITHUB_OAUTH_ENABLED: true # also support google oauth
      # KOMODO_GITHUB_OAUTH_ID: your_oauth_id
      # KOMODO_GITHUB_OAUTH_SECRET: your_oauth_secret
      ## AWS
      # KOMODO_AWS_ACCESS_KEY_ID: your_aws_key_id
      # KOMODO_AWS_SECRET_ACCESS_KEY: your_secret_access_key
      ## HETZNER
      # KOMODO_HETZNER_TOKEN: your_hetzner_token

  komodo-mongo:
    image: mongo
    command: --quiet # suppress mongo logs a bit
    restart: unless-stopped
    logging:
      driver: local
    networks:
      - komodo-network
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # change these
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  db-data:
  db-config:

networks:
  komodo-network: {}